version: '3.1'

services:

  mongonbd:
    image: mongo
    restart: always
    ports:
        - "2717:27017"
    volumes: 
        - ./import:/home/import/
        - ./results:/home/results/
        - ./queries:/home/queries/